apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-deployment
  labels:
    app: spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
        - name: deploment-container-name
          image: igal2323/spa-demo:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spa-loadbalancer
spec:
  selector:
    app: spa
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30023
