apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: docker.io/igal2323/api
        name: api
        imagePullPolicy: Always
        ports:
          - containerPort: 32767 
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    run: api
spec:
  ports:
  - port: 32767
    protocol: TCP
    targetPort: 32767
  selector:
    app: api
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: api-loadbalancer
#spec:
#  selector:
#    app: api
#  type: LoadBalancer
#  ports:
#    - protocol: TCP
#      port: 32767
#      targetPort: 32767
#      nodePort: 30026
